//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoii
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KursoviiEntities : DbContext
    {
        public KursoviiEntities()
            : base("name=KursoviiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Данные_о_пассажирах> Данные_о_пассажирах { get; set; }
        public virtual DbSet<Записи_на_рейс> Записи_на_рейс { get; set; }
        public virtual DbSet<История_входа> История_входа { get; set; }
        public virtual DbSet<Паспорт_пассажира> Паспорт_пассажира { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Рейс> Рейс { get; set; }
        public virtual DbSet<Самолёты> Самолёты { get; set; }
        public virtual DbSet<Статус_пользователя> Статус_пользователя { get; set; }
        public virtual DbSet<Статус_рейса> Статус_рейса { get; set; }
    }
}
