//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoii
{
    using System;
    using System.Collections.Generic;
    
    public partial class Данные_о_пассажирах
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Данные_о_пассажирах()
        {
            this.Записи_на_рейс = new HashSet<Записи_на_рейс>();
        }
    
        public int Код_пассажира { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public Nullable<int> Код_пасспорта { get; set; }
    
        public virtual Паспорт_пассажира Паспорт_пассажира { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Записи_на_рейс> Записи_на_рейс { get; set; }
    }
}
