//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoii
{
    using System;
    using System.Collections.Generic;
    
    public partial class Записи_на_рейс
    {
        public int Код_записи { get; set; }
        public Nullable<int> Код_рейса { get; set; }
        public Nullable<int> Код_пассажира { get; set; }
        public Nullable<System.DateTime> Дата_записи { get; set; }
    
        public virtual Данные_о_пассажирах Данные_о_пассажирах { get; set; }
        public virtual Рейс Рейс { get; set; }
    }
}
