//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoii
{
    using System;
    using System.Collections.Generic;
    
    public partial class Паспорт_пассажира
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Паспорт_пассажира()
        {
            this.Данные_о_пассажирах = new HashSet<Данные_о_пассажирах>();
        }
    
        public int Код_паспорта { get; set; }
        public string Серия { get; set; }
        public string Номер { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Данные_о_пассажирах> Данные_о_пассажирах { get; set; }
    }
}
