//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoii
{
    using System;
    using System.Collections.Generic;
    
    public partial class Рейс
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Рейс()
        {
            this.Записи_на_рейс = new HashSet<Записи_на_рейс>();
        }
    
        public int Код_рейса { get; set; }
        public Nullable<System.DateTime> Дата_полёта { get; set; }
        public Nullable<int> Код_самолёта { get; set; }
        public string Город_отправки { get; set; }
        public string Город_прибытия { get; set; }
        public Nullable<int> Код_статуса_рейса { get; set; }
        public Nullable<int> Код_сотрудника { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Записи_на_рейс> Записи_на_рейс { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Самолёты Самолёты { get; set; }
        public virtual Статус_рейса Статус_рейса { get; set; }
    }
}
