//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoii
{
    using System;
    using System.Collections.Generic;
    
    public partial class Самолёты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Самолёты()
        {
            this.Рейс = new HashSet<Рейс>();
        }
    
        public int Код_самолёта { get; set; }
        public string Название_самолёта { get; set; }
        public Nullable<int> Вместительность_людей { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Рейс> Рейс { get; set; }
    }
}
